name: Tests and coverage

on:
  push:    
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
      # - name: Analyze
        # run: flutter analyze
      - name: Import files to coverage
        run: sh test/helpers/scripts/coverage_imports.sh tag_ui
      - name: Run tests
        run: flutter test --coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

